// <auto-generated />
namespace app_talimpo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class fixpedidos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixpedidos));
        
        string IMigrationMetadata.Id
        {
            get { return "201801290109585_fixpedidos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
